---
abstract: "a wrap of Win32::OLE excel\r"
author:
  - 'xiaoyafeng <xyf.xiao@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-ExcelSimple
no_index:
  directory:
    - inc
requires:
  Win32::OLE: 0.17
version: 0.53
